// app/build.gradle
plugins {
    id 'com.android.application'
}

android {
    compileSdk 33
    namespace 'com.stealth.app'

    defaultConfig {
        applicationId "com.stealth.app"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true         // Obfuscate code
            shrinkResources true       // Remove unused resources
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.10.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.activity:activity:1.7.2'
}